### ISSUE TITLE
OSD broken in X since wayland compiled in

### ISSUE THREAD

**Issue by bell07** [Ryochan7/sc-controller#77]
I enabled systemwide USE=wayland in my Gentoo and lost OSD functionality in sc-controller.
I am still on X with Xfce4. The issue persist with `USE="-wayland" emerge sc-controller`
The next error appears if I try to call the osd main menu.

```
$ /usr/bin/python3.10 /usr/lib/python3.10/site-packages/scc/x11/scc-osd-daemon.py debug
D OSD DaemonCtrl    Connected to daemon, version 0.4.8.9
D OSD DaemonCtrl    Daemon reported profile change for deck3:3: /home/player/.config/scc/profiles/XBox Controller.sccprofile
D OSD DaemonCtrl    Daemon is ready.
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
/usr/lib/python3.10/site-packages/scc/osd/__init__.py:56: PyGIWarning: GtkLayerShell was imported without specifying a version first. Use gi.require_version('GtkLayerShell', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import GtkLayerShell
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/scc/x11/scc-osd-daemon.py", line 222, in on_unknown_message
    self._window = Menu()
  File "/usr/lib/python3.10/site-packages/scc/osd/menu.py", line 45, in __init__
    OSDWindow.__init__(self, cls, layer)
  File "/usr/lib/python3.10/site-packages/scc/osd/__init__.py", line 57, in __init__
    if GtkLayerShell.is_supported():
  File "/usr/lib/python3.10/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.GtkLayerShell' object has no attribute 'is_supported'
D OSD DaemonCtrl    Connection to daemon lost
E OSD osd.daemon    Connection to daemon lost

```

**Comment by bell07** [comment]
Got it. Issue was caused by stable gui-libs/gtk-layer-shell-0.1.0-r1. Testing version gui-libs/gtk-layer-shell.0.7.0 does work as expected. Gentoo ebuild should be adjusted
