### ISSUE TITLE
On-screen keyboard didn't work properly

### ISSUE THREAD

**Issue by Arbars** [Ryochan7/sc-controller#90]
Hi! Thank you for your work!

When trying to run `scc osd-keyboard`, program shows this:

```
scc osd-keyboard

(scc:4866): dbind-WARNING **: 18:58:55.590: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "/usr/bin/scc", line 9, in <module>
    main()
  File "/usr/lib64/python3/site-packages/scc/scripts.py", line 389, in main
    sys.exit(command(sys.argv[0], sys.argv[2:]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/scc/scripts.py", line 79, in cmd_osd_keyboard
    return run_osd_tool(Keyboard(), argv0, argv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/scc/scripts.py", line 334, in run_osd_tool
    tool.run()
  File "/usr/lib64/python3/site-packages/scc/osd/keyboard.py", line 493, in run
    OSDWindow.run(self)
  File "/usr/lib64/python3/site-packages/scc/osd/__init__.py", line 261, in run
    self.show()
  File "/usr/lib64/python3/site-packages/scc/osd/keyboard.py", line 564, in show
    self._create_background()
  File "/usr/lib64/python3/site-packages/scc/osd/keyboard.py", line 346, in _create_background
    self.background = KeyboardImage(self.args.image)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/scc/osd/keyboard.py", line 77, in __init__
    self._help_areas = [ self.get_limit("HELP_LEFT"), self.get_limit("HELP_RIGHT") ]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3/site-packages/scc/osd/keyboard.py", line 124, in get_limit
    if not hasattr(a, "parent"): a.parent = None
                                 ^^^^^^^^
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'parent'
```
When I start keyboard from GUI, it's show this:
![Screenshot_20230702_194750](https://github.com/Ryochan7/sc-controller/assets/10302498/7cb98dd3-861e-4dc2-98b6-a53d7ba21895)

**Comment by C0rn3j** [comment]
I have not tested the launch from GUI (I am on wayland and it's completely broken there iirc) , but I can confirm the `scc osd-keyboard` issue and that it also is resolved in current git master.

@Ryochan7 would it be possible to tag a release to fix this (partially or completely) and get the recent additions in too?
